config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#index'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :articles
  resources :tweets
  resources :members
  resources :journals

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_secure_password
  def editor?
    self.role = 'editor'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  #authentication
  # black list everything
  before_action :authenticate

  def authenticate
    unless logged_in
     flash[:error] = "You must be logged in to access this section of the site"
     redirect_to login_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  #allows for front page with all articles to show first before login
  skip_before_action :authenticate, only: [:index]

  def index
    @current_uri = request.env['PATH_INFO']
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]
  # before_action :require_user, only: [:index, :show]
  def login
  end

  def show
    @member = Member.find(params[:id])
    unless @member.id == @current_user.id
      flash[:notice] = "You don't have access other member pages!"
      redirect_to member_path(@current_user)
      return
    end
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new member_params
    @member.save
    redirect_to root_path
  end
  def edit
    @member = Member.find(params[:id])
  end
  def update
    @member = Member.find(params[:id])
    @member.update(member_params)

    redirect_to member_path(@member)
  end

  private

  def member_params
    params.require(:member).permit(:username, :calorie_intake,:calorie_intake_goal, :minutes_exercised,:minutes_exercised_goal, :password, :password_confirmation,
    :steps,:steps_goal, :miles,:miles_goal, :calories_burned,:calories_burned_goal, :weight,:weight_goal, :sleep,:sleep_goal, :blood_sugar,:blood_sugar_goal)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #authentication
  skip_before_action :authenticate, only: [:new, :create]
  def new
    @member = Member.new
  end

  def create
    user = Member.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to member_path(user)
    else
      flash.now[:danger] = "Invalid username/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user = @current_user || Member.find_by(id: session[:user_id])
  end

  # def require_user
  #   redirect_to '/login' unless current_user
  # end

  def logged_in
  #  not nil = true; there is a current user?
   !current_user.nil?
  end

  def log_out
   session.delete :user_id
   @current_user = nil
  end
end

app/views/homes/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZeusJuice</title>
<link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
</head>
<body>
  <header>
    <h1 id="logo"><a href="/" style="color: black; text-decoration:none;"><span style="color: white;">z</span>Fit</a></h1>
    <!-- sub logo -->
    <h2 id="sub-logo">GET HEALTHY</h2>
    <!-- login, sign up, and page nav area -->
    <div id="login-sign-up">
      <% if logged_in %>
          Welcome <%= @current_user.username%> |
          <%= link_to 'Profile', member_path(@current_user)%> |
          <%= link_to 'Logout', logout_path, :method => :delete %>
      <% else %>
          <%= link_to "Login", login_path %> |
          <%= link_to "Sign Up", new_member_path%>
      <% end %>
    </div>
  </header>

  <section id="about">
    <article>
      <h1 style="padding: 60px; font-size: 43px; display: inline-block; margin-bottom: 20px; padding-bottom: 10px">What is zFit?</h1>
      <p style="padding: 10px 80px; width: 600px">
        zFit is the premier fitness and health website that enables you to track your fitness and health goals, become inspired to set new ones, and encourage friends to stay healthy and fit too.
      </p>
    </article>
    <article>
      <h1 style="padding: 60px; font-size: 43px; display: inline-block; margin-bottom: 20px; padding-bottom: 10px">Why zFit?</h1>
      <p style="padding: 10px 80px; width: 600px">
        Are you struggling to achieve your fitness and health goals? Are you the type of person that needs constant reminders to keep on top of your goals?  Are you looking for community to support you on your path to a healthy life?

        Then zFit is for YOU!  Sign up now at the link above!
      </p>
    </article>
    <img src="https://upload.wikimedia.org/wikipedia/commons/b/b0/Running_icon_-_Noun_Project_17825.svg" alt="running icon from wikimedia commons" style="width: 300px; position: relative; top: -380px; left: 850px;" />
  </section>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>zFit</title>
<link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if @current_uri != root_path %>
    <div class="other-header">
      <h1 style="font-size: 40px; font-family: 'Raleway', sans-serif; text-align: center;">zFit
      </h1>
    </div>
  <% end %>
<%= yield %>

<!-- <% if @current_uri != root_path %>
<footer>
  <div>
    <p>
      &copy; zFit 2015
    </p>
  </div>
</footer>
<% end %> -->

</body>
</html>

app/views/members/new.html.erb
<div style="text-align: center; margin: 0 auto;">
<h1> Sign Up</h1>
<%= form_for @member do |f| %>
<% flash.each do |message_type, message| %>
     <div class="alert"-<%= message_type %>"><h1><%= message %></h1></div>
   <% end %>
  <p>
    <%= f.label :username, "Username: "%>
    <%= f.text_field :username%>
  </p>
  <p>
    <%= f.label :password, "Password: "%>
    <%= f.password_field :password%>
  </p>
  <p>
    <%= f.label :password_confirmation, "Password Confirmation: "%>
    <%= f.password_field :password_confirmation%>
  </p>
  <p>
    <%= f.submit "Sign Up!"%>
  </p>
<% end %>
</div>

app/views/members/show.html.erb
<!-- TODO: Look at new layout, with idea to incorporate D3 graphing as part of tracking with focus on diabetes managment -->
<!-- TODO: Incorporate USDA API integration for meal/food search -->
<!-- TODO: Think about create a general form for people to include more trackers as they see fit -->
<!-- Login/Logout form  -->
<div id="login-sign-up">
  <% if logged_in %>
      Welcome <%= @current_user.username%> |
      <%= link_to 'Logout', logout_path, :method => :delete %></div>
  <% end %>
</div>
<% flash.each do |message_type, message| %>
     <div class="alert"-<%= message_type %>"><h1><%= message %></h1></div>
<% end %>
<div class="stats-holding-container">
  <!-- Stats container -->
  <div class="member-page-containers">
    <h2>Stats</h2>
      <!-- CALORIES INTAKE FORM -->
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
          <%= f.label :calorie_intake, "Calorie Intake"%>
          <%= f.number_field :calorie_intake, :style => "width: 60px;"%>
          <%= f.submit "Update Calories" %>
        </div>
      <%end%>
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
          <%= f.label :calorie_intake_goal, "Daily Goal"%>
          <%= f.number_field :calorie_intake_goal, :style => "width: 60px;"%>
          <%= f.submit "Update Goal" %>
        </div>
      <%end%>
      <!-- CALORIES INTAKE CALCULATION AND TRACKING BAR-->
      <% daily_calorie_percent = @member.calorie_intake.to_f/@member.calorie_intake_goal.to_f*100%>
      <div style="width: 100%; height: 20px; background: linear-gradient(to right, red 0%, red <%= daily_calorie_percent%>%, white <%= daily_calorie_percent%>%); border: 1px solid black;"></div>
      <hr>
      <!-- CALORIES BURNED EXERCISED FORM -->
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :calories_burned , "Calories Burned"%>
        <%= f.number_field :calories_burned, :style => "width: 60px;" %>
        <%= f.submit "Update Calories Burned" %>
        </div>
      <%end%>
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :calories_burned_goal , "Daily Goal"%>
        <%= f.number_field :calories_burned_goal, :style => "width: 60px;" %>
        <%= f.submit "Update Goal" %>
        </div>
      <%end%>
      <!-- CALORIES BURNED CALCULATION AND TRACKING BAR-->
      <% daily_calorie_burned_percent = @member.calories_burned.to_f/@member.calories_burned_goal.to_f*100%>
      <div style="width: 100%; height: 20px; background: linear-gradient(to right, red 0%, red <%= daily_calorie_burned_percent %>%, white <%= daily_calorie_burned_percent%>%); border: 1px solid black;"></div>
      <hr>
      <!--  MINUTES EXERCISED FORM -->
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :minutes_exercised , "Minutes Exercised"%>
        <%= f.number_field :minutes_exercised, :style => "width: 60px;" %>
        <%= f.submit "Update Minutes" %>
        </div>
      <%end%>
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :minutes_exercised_goal , "Daily Goal"%>
        <%= f.number_field :minutes_exercised_goal, :style => "width: 60px;" %>
        <%= f.submit "Update Goal" %>
        </div>
      <%end%>
      <!-- MINUTES EXERCISED CALCULATION AND TRACKING BAR-->
      <% daily_minutes_exercised_percent = @member.minutes_exercised.to_f/@member.minutes_exercised_goal.to_f*100%>
      <div style="width: 100%; height: 20px; background: linear-gradient(to right, red 0%, red <%= daily_minutes_exercised_percent %>%, white <%= daily_minutes_exercised_percent %>%); border: 1px solid black;"></div>
      <hr>
      <!-- MILES EXERCISED FORM -->
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :miles , "Miles"%>
        <%= f.number_field :miles, :style => "width: 60px;" %>
        <%= f.submit "Update Miles" %>
        </div>
      <%end%>
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :miles_goal , "Goal"%>
        <%= f.number_field :miles_goal, :style => "width: 60px;" %>
        <%= f.submit "Update Goal" %>
        </div>
      <%end%>
      <!-- MILE EXERCISED CALCULATION AND TRACKING BAR-->
      <% daily_miles_exercised_percent = @member.miles.to_f/@member.miles_goal.to_f*100%>
      <div style="width: 100%; height: 20px; background: linear-gradient(to right, red 0%, red <%= daily_miles_exercised_percent %>%, white <%= daily_miles_exercised_percent %>%); border: 1px solid black;"></div>
      <hr>
      <!-- STEPS EXERCISED FORM -->
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :steps , "Steps Exercised"%>
        <%= f.number_field :steps, :style => "width: 60px;" %>
        <%= f.submit "Update Steps" %>
        </div>
      <%end%>
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :steps_goal , "Daily Goal"%>
        <%= f.number_field :steps_goal, :style => "width: 60px;" %>
        <%= f.submit "Update Goal" %>
        </div>
      <%end%>
      <!-- STEPS EXERCISED CALCULATION AND TRACKING BAR-->
      <% daily_steps_percent = @member.steps.to_f/@member.steps_goal.to_f*100%>
      <div style="width: 100%; height: 20px; background: linear-gradient(to right, red 0%, red <%= daily_steps_percent %>%, white <%= daily_steps_percent %>%); border: 1px solid black;"></div>
      <hr>
      <!-- BLOOD SUGAR FORM -->
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :blood_sugar , "Blood Sugar"%>
        <%= f.number_field :blood_sugar, :style => "width: 60px;"  %>
        <%= f.submit "Update Blood Sugar" %>
        </div>
      <%end%>
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :blood_sugar_goal , "Each Time Goal"%>
        <%= f.number_field :blood_sugar_goal, :style => "width: 60px;"  %>
        <%= f.submit "Update Goal" %>
        </div>
      <%end%>
      <!-- BLOOD SUGAR CALCULATION AND TRACKING BAR-->
      <% daily_blood_sugar_percent = @member.blood_sugar.to_f/@member.blood_sugar_goal.to_f*100%>
      <div style="width: 100%; height: 20px; background: linear-gradient(to right, red 0%, red <%= daily_blood_sugar_percent %>%, white <%= daily_blood_sugar_percent %>%); border: 1px solid black;"></div>
      <hr>
      <!-- SLEEP EXERCISED FORM -->
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :sleep , "Sleep"%>
        <%= f.number_field :sleep, :style => "width: 60px;" %>
        <%= f.submit "Update Sleep" %>
        </div>
      <%end%>
      <%= form_for @member do |f|%>
        <div style="padding-bottom: 4px;">
        <%= f.label :sleep_goal , "Nightly Goal"%>
        <%= f.number_field :sleep_goal, :style => "width: 60px;" %>
        <%= f.submit "Update Goal" %>
        </div>
      <%end%>
      <!-- SLEEP CALCULATION AND TRACKING BAR-->
      <% daily_sleep_percent = @member.sleep.to_f/@member.sleep_goal.to_f*100%>
      <div style="width: 100%; height: 20px; background: linear-gradient(to right, red 0%, red <%= daily_sleep_percent %>%, white <%= daily_sleep_percent %>%); border: 1px solid black;"></div>
      <hr>
  </div>
</div>